# Generated by Django 4.0.2 on 2022-02-08 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=50)),
                ('bus_no', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=48)),
                ('bus_type', models.CharField(default='Seater', max_length=50, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tripschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('departure_time', models.CharField(blank=True, max_length=20, null=True)),
                ('arrival_time', models.CharField(blank=True, max_length=20, null=True)),
                ('available_seat', models.IntegerField(default=48, null=True)),
                ('ticket_sold', models.IntegerField(default=0, null=True)),
                ('price', models.FloatField()),
                ('journey_time', models.CharField(max_length=25, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('destination', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
                ('bus_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bus')),
                ('trip_schedule_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0.0)),
                ('number_of_seats', models.IntegerField(default=0)),
                ('seat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('boarding_point', models.CharField(max_length=50, null=True)),
                ('dropping_point', models.CharField(max_length=50, null=True)),
                ('booked', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('trip_schedule_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tripschedule')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=100, null=True)),
                ('ticket_id', models.IntegerField()),
                ('bus_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DroppingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_location', models.CharField(max_length=50, null=True)),
                ('trip_schedule_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tripschedule')),
            ],
        ),
        migrations.CreateModel(
            name='BoardingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_location', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('trip_schedule_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tripschedule')),
            ],
        ),
    ]
