# Generated by Django 4.0.2 on 2022-02-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tripschedule_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripschedule',
            name='trip_schedule_agent',
        ),
    ]
