# Generated by Django 4.0.2 on 2022-02-11 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tripschedule_bus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripschedule',
            name='bus_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bus'),
        ),
    ]
