# Generated by Django 4.0.2 on 2022-05-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ticket_ticket_number_userinfo_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ticket'),
        ),
    ]
