# Generated by Django 4.0.2 on 2022-05-01 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userinfo_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='ticket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ticket'),
        ),
    ]
