# Generated by Django 4.0.2 on 2022-08-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_seat_ticket_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charge_id',
            new_name='payment_id',
        ),
    ]
