# Generated by Django 4.0.2 on 2022-08-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_stripe_charge_id_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
