# Generated by Django 4.0.2 on 2022-08-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_payment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
