# Generated by Django 4.0.2 on 2022-09-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_userinfo_passengerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripschedule',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
