# Generated by Django 4.0.2 on 2022-09-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_tripschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
