# Generated by Django 4.0.2 on 2022-09-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_bus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripschedule',
            name='trip_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
