# Generated by Django 4.0.2 on 2022-02-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
    ]
