# Generated by Django 4.0.2 on 2022-05-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraccount_is_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
    ]
