# Generated by Django 4.0.2 on 2022-09-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useraccount_city_useraccount_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='pancard_number',
        ),
    ]
