# Generated by Django 4.0.2 on 2022-09-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_useraccount_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='organization_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pancard_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
