# Generated by Django 4.0.2 on 2022-09-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_useraccount_city_useraccount_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='organization_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='pancard_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
