# Generated by Django 4.0.2 on 2022-09-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_remove_agentinformation_agent_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentinformation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='agentinformation',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='agentinformation',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='agentinformation',
            name='pancard_number',
        ),
        migrations.RemoveField(
            model_name='agentinformation',
            name='user',
        ),
    ]
