export const SET_SEAT_DATA = 'SET_SEAT_DATA';
export const REMOVE_SEAT_DATA = 'REMOVE_SEAT_DATA';
export const REQUEST_ADD_BOARDINGPOINT_DATA = 'REQUEST_ADD_BOARDINGPOINT_DATA';
export const REQUEST_DELETE_BOARDINGPOINT_DATA = 'REQUEST_DELETE_BOARDINGPOINT_DATA'
export const REQUEST_ADD_DROPPINGPOINT_DATA = 'REQUEST_ADD_DROPPINGPOINT_DATA';
export const REQUEST_DELETE_DROPPINGPOINT_DATA = 'REQUEST_DELETE_DROPPINGPOINT_DATA'